# Generated by Django 5.1.2 on 2024-11-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم التخصص')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم جهة التدريب')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('contact_person', models.CharField(max_length=255, verbose_name='اسم جهة الاتصال')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني لجهة الاتصال')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='رقم هاتف جهة الاتصال')),
                ('available_slots', models.PositiveIntegerField(verbose_name='عدد الفرص المتاحة')),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى'), ('both', 'كلاهما')], max_length=10, verbose_name='الجنس المقبول')),
                ('specializations', models.ManyToManyField(to='training_entities.specialization', verbose_name='التخصصات')),
            ],
        ),
    ]
