# Generated by Django 5.1.2 on 2024-11-08 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training_entities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEvaluationCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion_number', models.PositiveIntegerField(choices=[(1, 'المحافظة على أوقات الدوام.'), (2, 'الالتزام بإجراءات وأنظمة العمل.'), (3, 'المظهر العام للمتدرب.')], verbose_name='رقم المعيار')),
                ('description', models.CharField(max_length=255, verbose_name='وصف المعيار')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingEntityEvaluationCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion_number', models.PositiveIntegerField(choices=[(1, 'جدية التدريب.'), (2, 'الخبرة التي يقدمها التدريب.'), (3, 'مناسبة مكان التدريب.')], verbose_name='رقم المعيار')),
                ('description', models.CharField(max_length=255, verbose_name='وصف المعيار')),
            ],
        ),
        migrations.CreateModel(
            name='StudentEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم')),
                ('total_score', models.PositiveIntegerField(default=0, verbose_name='المجموع النهائي')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_evaluations_given', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_evaluations_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentEvaluationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(choices=[(10, 'ممتاز'), (8, 'جيد جدا'), (6, 'جيد'), (4, 'مقبول'), (2, 'ضعيف')], verbose_name='الدرجة')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.studentevaluationcriterion')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria_scores', to='evaluations.studentevaluation')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingEntityEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم')),
                ('total_score', models.PositiveIntegerField(default=0, verbose_name='المجموع النهائي')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_evaluations_given', to=settings.AUTH_USER_MODEL)),
                ('training_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_received', to='training_entities.trainingentity')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingEntityEvaluationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(choices=[(10, 'ممتاز'), (8, 'جيد جدا'), (6, 'جيد'), (4, 'مقبول'), (2, 'ضعيف')], verbose_name='الدرجة')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.trainingentityevaluationcriterion')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria_scores', to='evaluations.trainingentityevaluation')),
            ],
        ),
    ]
